# Esse arquivo fica em: /etc/prometheus/
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: "primeiro-exporter"
    static_configs:
      - targets: ["0.0.0.0:8899"]
