# Esse arquivo fica em: /etc/prometheus/
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: "primeiro_exporter"
    static_configs:
      - targets: ["192.168.0.81:8899"]
  - job_name: "segundo_exporter"
    static_configs:
      - targets: ["192.168.0.81:7788"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["192.168.0.82:9100"]